#include "defs.h"

float skill;
float coop;

//typedef void (float n) f_void_float;

// status bar stuff
.string status_string;           // current centerprint text
.float status_string_lines;       // how many lines the centerprint is
.float status_string_time;        // when text will time out
.float status_string_refresh_time;       // when sbar is next printed

.float team_no;
//.f_void_float menu_input;
.float menu;
.float class;